### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Osue1** [Osue1/protospace-38186#2]
# URL
https://protospace-38186.herokuapp.com/

**Comment by motomuun** [comment]
@Osue1 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**コメント機能**

- [ ] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
空のまま投稿した場合、下記エラーページに遷移します。遷移せず、そのページに留まれるように修正をお願いします。


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by motomuun** [comment]
@Osue1 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
